import os

env = Environment()

path_to_product_packager="/absolute/path/to/scons/folder"

env["src"] = os.getcwd()

env["BUILD_DIR"] = env["src"] + "/build/"
env["DIST_DIR"] =  env["src"] + "/dist/"

Export("env")
SConscript(path_to_product_packager + "/SConstruct")
