from pathlib import Path
from enum import Enum
from typing import Iterator

import scons_helper as sh
from SCons.Script import Dir, Environment, Export, File, Import, AddOption, Return

# BEGIN - auto-completion
env = Environment()
# END - auto-completion

Import("env")

AddOption("--strict", action="store_true", dest="strict")
AddOption("--epub", action="store_true", dest="epub")
AddOption("--mavenseed", action="store_true", dest="mavenseed")


class Error(Enum):
    SOURCE_DIR_INVALID = 1
    GIT_VERSIONS_DONT_MATCH = 2
    MISSING_GODOT_PROJECT_NAME = 3


def validate_source_directory() -> None:
    """Ensures the source directory contains a content folder."""
    is_source_directory_valid: bool = env["SRC_DIR"].Dir("content").exists()
    if not is_source_directory_valid:
        sh.print_error(f"ERROR: {env['SRC_DIR']} is not a valid source directory!")
        env.Exit(Error.SOURCE_DIR_INVALID)


def try_package_godot_projects() -> None:
    def get_godot_project_name(project_file: File) -> str:
        """Return the project name from a directory with a project.godot file."""
        prefix = "config/name="
        godot_project_name = ""

        with open(str(project_file), "r") as pf:
            for line in pf:
                if line.startswith(prefix):
                    godot_project_name = (
                        line.lstrip(prefix).replace(" ", "_").replace('"', "").strip()
                    )
        return godot_project_name

    for godot_project_file in sh.get_godot_project_files(env["SRC_DIR"]):
        godot_project_name = get_godot_project_name(godot_project_file)

        if godot_project_name == "":
            sh.print_error(
                f"ERROR: Missing Godot project name in {godot_project_file}!"
            )
            env.Exit(Error.MISSING_GODOT_PROJECT_NAME)

        env.Command(
            target=env["DIST_DIR"].File(godot_project_name + ".zip"),
            source=godot_project_file.Dir("."),
            action=[
                [
                    env.File("package_godot_project.py"),
                    "$SOURCE",
                    "--output",
                    "${TARGET.dir}",
                    "--title",
                    godot_project_name,
                ],
            ],
        )


def make_strict_mode_checks():
    if not sh.validate_git_versions(env["SRC_DIR"]):
        sh.print_error(
            "ERROR: The Git version of submodules does not match the required version!"
        )
        env.Exit(Error.GIT_VERSIONS_DONT_MATCH)


def glob_extensions(dir: Dir, extensions: list[str]) -> Iterator[File]:
    """Return all files in the given path with an extension in the extension list."""
    return (File(f) for e in extensions for f in Path(str(dir)).glob("**/" + e))


def find_subdirectories(content_dir: Dir) -> list[Dir]:
    """Returns a list of folders within the content folder"""
    content_path_dir = Path(str(content_dir))
    return [Dir(str(d)) for d in content_path_dir.iterdir() if d.is_dir()]


validate_source_directory()
if env.GetOption("strict"):
    make_strict_mode_checks()

env["CONTENT_DIR"] = env["SRC_DIR"].Dir("content")
env["CONTENT_DIRS"] = find_subdirectories(env["CONTENT_DIR"])
env["MEDIA_FILES"] = [
    f
    for d in env["CONTENT_DIRS"]
    for f in glob_extensions(d, ["*.png", "*.jpg", "*.jpeg", "*.svg", "*.gif", "*.mp4"])
]
env["MARKDOWN_FILES"] = [
    f for d in env["CONTENT_DIRS"] for f in glob_extensions(d, ["*.md"])
]

# Make environment variables available to subscripts
Export("env")

try_package_godot_projects()
if env.GetOption("epub"):
    env.SConscript("EpubSCsub")
else:
    mavenseed_files = env.SConscript("SCsub")
    Return("mavenseed_files")
