name: Build Formatter
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-mingw@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.0'
      - run: |
          nimble install honeycomb
          cd src
          nim c -d:release -o:gdquest-format format
          nim c -d:release -d:mingw -o:gdquest-format format
          mkdir -p release
          mv gdquest-* release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gdquest-format
          path: src/release
