name: Build Product Packager Nim Suite

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-mingw@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.0'
      - run: |
          nimble build
          nimble build -d:mingw
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gdquest-product-packager
          path: bin
