name: Release Product Packager Nim Suite

on:
  workflow_dispatch:

  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Mingw
        uses: egor-tensin/setup-mingw@v2
      - name: Setup Nim Action
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.4'
      - run: |
          git clone -b '3.4' --single-branch https://github.com/godotengine/godot.git
          nimble -y build
          nimble -y build -d:mingw
      - name: Generate Changelog
        run: echo "GDQuest Product Manager" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          append_body: true
          files: |
            gdquest-product-packager
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}